### ISSUE TITLE
Implementation Details

### ISSUE THREAD

**Issue by qqueue** [aeosynth/sleepover#2]
Continuing the discussion from #1.

* How will `sleepover` look and act?
* How will the frontend code be structured?
* How will we build/test the frontend?
* What will our signaling/accounts backend be like?

\>arguan
\>implementan
\>hipsteran

**Comment by vendethiel** [comment]
¯\_(ツ)_/¯

**Comment by aeosynth** [comment]
if someone wants ownership of this just ask

**Comment by vendethiel** [comment]
there's not much to ask for

**Comment by aeosynth** [comment]
maybe i should delete the repo. or we could pivot into something more interesting?

**Comment by vendethiel** [comment]
I don't know. I just come here once in a while to find the name of some stuff we talked about.

**Comment by aeosynth** [comment]
i'll just delete it

rip
